basic.forever(function on_forever() {
    basic.showIcon(IconNames.Heart)
    basic.clearScreen()
    basic.pause(500)
    basic.showIcon(IconNames.SmallHeart)
    basic.clearScreen()
    basic.pause(500)
    basic.showIcon(IconNames.Heart)
    basic.showArrow(ArrowNames.SouthEast)
    basic.clearScreen()
    basic.showIcon(IconNames.Ghost)
})
